"""song and history 2

Revision ID: 537252b2b1ac
Revises: 
Create Date: 2025-07-07 18:06:18.219369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537252b2b1ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('artist', sa.String(length=64), nullable=False),
    sa.Column('album', sa.String(length=120), nullable=True),
    sa.Column('album_picture', sa.String(length=120), nullable=True),
    sa.Column('album_release_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'artist', name='_title_artist_uc')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_album'), ['album'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_album_release_date'), ['album_release_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_artist'), ['artist'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_title'), ['title'], unique=False)

    op.create_table('played_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('played_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_played_history_song_id'), ['song_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_played_history_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('played_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_played_history_timestamp'))
        batch_op.drop_index(batch_op.f('ix_played_history_song_id'))

    op.drop_table('played_history')
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_title'))
        batch_op.drop_index(batch_op.f('ix_song_artist'))
        batch_op.drop_index(batch_op.f('ix_song_album_release_date'))
        batch_op.drop_index(batch_op.f('ix_song_album'))

    op.drop_table('song')
    # ### end Alembic commands ###
