"""modified album release date

Revision ID: a3187456882d
Revises: 537252b2b1ac
Create Date: 2025-07-07 22:25:39.191046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3187456882d'
down_revision = '537252b2b1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('album_release_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.alter_column('album_release_date',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
